Rc2 2
benjie/repo pull request #22
Opened 2017-03-02 09:36 UTC by benjie

2017-03-02 09:36 UTC, benjie commented
Depends: #19

2017-03-02 09:36 UTC, benjie commented
Depends: #20

2017-03-02 09:41 UTC, benjie commented
Depends: #21

2017-03-02 12:27 UTC, jemgillam approved these changes
I approve of this message!

2017-03-02 12:30 UTC, jemgillam requested changes
Wait a minute...

2017-03-02 12:30 UTC, jemgillam reviewed
thinking...

2017-03-02 12:30 UTC, jemgillam approved these changes
Actually, yeah, this is good 👍

2017-03-12 11:00 UTC, closed without merging

2017-03-12 11:00 UTC, benjie commented
[BOTS] Closed issue because its has been inactive for 9 days (grace period: 5 days)